<a href="https://colab.research.google.com/github/JinLeeGG/Python_DataStructue-Algoritms/blob/main/3.%20Numpy/coding_Example/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy
- Most basic python library in data analysis using python
- It is widely used on its own with NumPy, but since it is also essential in various fields such as Pandas, machine learning, and more, it is a must-know library for Python developers.
- https://numpy.org/

### 1) Mathematical and Numerical Operations
- Supports summation, averaging, matrix operations, and more.

### 2) Fundamental Type
- Enables representation of multi-dimensional arrays using ndarray (n-dimensional array).

### 3) Why It's Needed Despite Python Lists
- Performance: Significantly faster than Python lists.
- Memory: Consumes less memory.
- Built-in Functions: Provides numerous numerical functions related to linear algebra and statistics.
- Wide Adoption: Many other modules use NumPy's function names and features directly.

<img width="500" src="https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" />

    - Scalar: 0 dimentional array(singular value)
    - Vector : 1 dimentional array
    - Matrix : 2 dimentional array
    - Tensor : 3 dimentional(beyond) array

In [1]:
import numpy as np

In [10]:
# 1st dementional array (vector)
# np.array(iterable)

arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])

In [11]:
# __repr__ : represent call (view)
arr1

array([1, 2, 3])

In [12]:
# as you can see the type is ndarray
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
#__str__ : Calling String
print(arr1)

[1 2 3]


In [8]:
# 0 dimentional : Scalar
# np.array(10)
print(np.array(10))

10


## Type promotion
- array requires all elements to be defined as 'one type'.
- Forces conversion to the largest of all types.

In [14]:
'''
NumPy Array: A NumPy array is homogeneous, meaning it can store elements
of only one data type (e.g., integers, floats). This allows for more efficient memory usage and operations.

Python List: A Python list is heterogeneous, meaning it can store elements
of different data types (e.g., integers, strings, objects) within the same list.

'''
# Type Promotion
arr1 = np.array([1,2,True, '김', 5.5])
print(arr1)
print(type(arr1))

# List
li1 = [1,2,True, '김', 5.5]
print(li1)
print(type(li1))


['1' '2' 'True' '김' '5.5']
<class 'numpy.ndarray'>
[1, 2, True, '김', 5.5]
<class 'list'>


In [15]:
# since an array contains an integer and float, it type promotes to the float type:
np.array([1,1,5.5,5,5])

array([1. , 1. , 5.5, 5. , 5. ])

## numpy field

In [17]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

### shape

- In numpy, we know the size of the array. By checking the shape, we can see how much data there is and in how many dimensions.
- The result of arr.shape is a tuple (rows, columns), which gives us the first dimension if there are only rows, and the second dimension if there is a matrix. You can also check the size by multiplying rows*columns.



In [19]:
arr3.shape

(5,)

### mdim
- Fields to determine how many dimensions of data you have

In [21]:
# equal to len(arr.shape)
arr3.ndim

1

### size
- number of datas

In [24]:
arr3.size

5

### len()
- array is an iterable object, so you can count its length.


In [25]:
len(arr3)

5