<a href="https://colab.research.google.com/github/JinLeeGG/Python_DataStructue-Algoritms/blob/main/(Day03)%20NumPy/1_%EB%84%98%ED%8C%8C%EC%9D%B4(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 (Numpy)
    - 파이썬을 활용한 데이터 분석에서 가장 기본이되는 라이브러리
    - 넘파이로만으로도 많이 사용되지만, 판다스(Pandas), 머신러닝 등 수 많은 분야에서 기본적으로 사용되므로, 파이썬 개발자라면 필수로 알아야하는 라이브러리이다.
    - https://numpy.org/

### 1) 수학 수치 연산
    - 합, 평균, 행렬연산 등이 가능하다

### 2) 기본 타입
    - ndarray(n-dimenstional array) 다차원 배열의 표연이 가능하다

### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다.
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다.
    - 그 외 수많은 모듈에서 numpy 함수명과 기능을 그대로 사용한다.



<img width="500" src="https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" />

    - Scalar: 0차원 array(단일값)
    - Vector : 1차원 array
    - Matrix : 2차원 array
    - Tensor : 3차원(이상) array

In [ ]:
import numpy as np

In [ ]:
# 1차원 array(백터) 생성
# np.array(iterable)

arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])

In [ ]:
# __repr__ : represent호출 (미리보기)
arr1

array([1, 2, 3])

In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
# __str__ : String호출
print(arr1)

[1 2 3]


In [ ]:
# 0차원 : Scalar
# np.array(10)
print(np.array(10))

10


## 타입 승격
    - array는 모든 원소가 '한 가지 타입' 으로 정의해야 한다.
    - 모든 타입 중 가장 큰 타입으로 강제로 변환한다.


In [ ]:
# List

li1 =  [1, 2, True, '김', 5.5]
print(li1)
print(type(li1))

# 타입 승격
arr1 = np.array([1, 2, True, '김', 5.5])
print(arr1)
print(type(arr1))


[1, 2, True, '김', 5.5]
<class 'list'>
['1' '2' 'True' '김' '5.5']
<class 'numpy.ndarray'>


In [ ]:
# 정수와 실수가 포함되어 있음으로 실수 타입으로 타입 승격한다.
np.array([1,1,5,5.5,5])

array([1. , 1. , 5. , 5.5, 5. ])

## numpy 필드

In [ ]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

### shape
    - numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서 몇개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
    - arr.shape의 경과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*열을 곱하면 크기도 확인할 수 있다.



In [ ]:
arr3.shape

(5,)

### mdim
    - 몇 차원 데이터인지 확인할 수 있는 필드


In [ ]:
# len(arr3.shape) 와 같다.
arr3.ndim

1

### size
  - 데이터의 개수

In [ ]:
arr3.size

5

### len()
  - array는 iterable한 객체이다. 따라서 길이를 셀 수 있다.

In [ ]:
len(arr3)

5

### dtype
  - 데이터의 타입
  

In [ ]:
# 정수는 8byte 이다.
arr3.dtype

dtype('int64')

##  numpy의 자료형
    - 부호가 있는 정수 int(8, 16, 32, 64)
    - 부호가 없는 정수 uint(8, 16, 32, 64)
    - 실수 float(16, 32, 64, 128)
    - x복소수 complex(64, 128 256)
    - 불리언 bool
    - x 문자열 string_
    - x 파이썬 오브젝트 object
    - x 유니코드 unicode_

## 2차원 array 생성

In [ ]:
arr5 = np.array([1,2,3,4])
arr6 = np.array([[5,6,7,8], [9,10,11,12]])

In [ ]:
arr5

array([1, 2, 3, 4])

In [ ]:
arr6

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(arr6.shape)
arr6

(2, 4)


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr6.ndim

2

In [ ]:
arr6.size

8

## 3차원 array

In [ ]:
arr7 = np.array([
          [
              [10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120],
          ],
          [
              [100, 200, 300, 400],
              [500, 600, 700, 800],
              [90, 1000, 1100, 1200],
          ]
      ])

In [ ]:
# 숫자가 3개니까 3차원
# 2*3*4 24 size
arr7.shape

(2, 3, 4)

In [ ]:
arr7.size

24

In [ ]:
arr7.ndim

3

## 같은 값이라도 차원이 다를 수 있다.
    - "차원 변환" 이 중요하다.

In [ ]:
np.array(10)

array(10)

In [ ]:
np.array([10])

array([10])

In [ ]:
np.array([[10]])

array([[10]])

In [ ]:
np.array([[[10]]])

array([[[10]]])

## np.arange
  - range()와 유사하다


In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
#numpy에 dtype을 붙여주면 그 타입으로 변경된다.
# np.arange(10, 0, -1, dtype=np.int16)
np.arange(10, 0, -1, dtype=np.int16).dtype


dtype('int16')

In [ ]:
#다른 타입으로 어레이를 복제하려면?
ar1 = np.arange(3,10)
ar1.dtype

dtype('int64')

## astype(타입)
    - 타입 변환한 array를 리턴(복제)
    - 원본 배열은 변화가 없다

In [ ]:
ar1_copy = ar1.astype(np.float32)
#오리지널 데이터는 안건드린다
print(ar1.dtype)
print(ar1)
#클론한 값만 변형된다.
print(ar1_copy.dtype)
print(ar1_copy)

int64
[3 4 5 6 7 8 9]
float32
[3. 4. 5. 6. 7. 8. 9.]


## reshape()
    - ndarray의 형태, 차원을 바꾸기 위해 사용한다.
    - 머신러닝, 데이터 프로세싱에서 매우 자주 사용되는 차원 변환.

In [ ]:
np.arange(12).reshape(2, 6)

#사이즈가 맞지 않아서 에러
# np.arange(12).reshape(2, 4)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# 3차원
print(np.arange(12).reshape(3, 2, 2).shape)
np.arange(12).reshape(3, 2, 2)

(3, 2, 2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## np.ones, np.zeros
    - array의 초기값을 설정
    - 1로 채울껀지(ones) 0으로 채울껀지(zeros)

In [ ]:
np.ones(5)
np.ones(5, dtype=np.int16)

array([1, 1, 1, 1, 1], dtype=int16)

In [ ]:
np.ones(6, dtype=np.int8).reshape(2, 3)


array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [ ]:
#부호가 없는 int값만 들어갈수 있다 +-값은 못들어간다.
np.zeros(10, dtype=np.uint8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
#3차원 매트릭스 구조로 자료구조가 들어간다.
np.zeros((3,2,5), dtype=np.uint8)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=uint8)

## 단위 행렬
    - 선형 대수학에서 사용되는 중요한 개념으로, 주어진 크기의 정사각형 행렬에서 주 대각서의 모든 원소는 1이고, 나머지 원소들은 0인 행렬을 의미한다
    - 머신러닝에서 데이터를 변환하거나 특정 모델을 학습할 때, 가중치 초기화나 수치 계산에서 단위 행렬을 사용한다.


In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## np.random 서브 모듈
    - rand : 0 ~ 1 사이의 균일 분포(uniform distribution) [균일하게 값들을 뽑아내는 방법]
    - randn : 가우시안 표준 정규 분포 [평균치의 값을 뽑아내는것]
    - randint : 균일 분포의 정규 난수



In [ ]:
# np.random.rand(개수)
# 0~1까지의 난수
np.random.rand(10)

array([0.48729573, 0.33556735, 0.06224875, 0.01914177, 0.92832714,
       0.50761296, 0.41012754, 0.07650328, 0.08700083, 0.29701745])

In [ ]:
#2행 3열로 만들수 있다. 다차원으로
np.random.rand(2,3)

array([[0.35660155, 0.48178675, 0.08510863],
       [0.12791655, 0.55849258, 0.05384015]])

<img width=300 src="https://thebook.io/img/080263/218.jpg" />

    1) 균일 분포
        - 균일 분포는 모든 값이 동일한 확률로 발생하는 분포

    2) 정규 분포 (가우시안 분포)
        - 정규 분포는 가장 일반적이고 중요한 연속 확률 분포로, 벨 모양의 대칭적 분포
        - 가장 많은 데이터가 평균 근처에 집중

In [ ]:
np.random.randn(5)

array([-1.68815631,  0.00759967,  0.97321689,  0.0582216 ,  0.0944499 ])

In [ ]:
# 0 ~ 5까지의 난수
np.random.randint(5)

2

In [ ]:
# [10, 20) 10 이상 20 미만
# (19, 20] 10초과 20 이하

# 10 이상 20 미만
np.random.randint(10, 20)

array([[[10, 12],
        [18, 13],
        [13, 16],
        [13, 18],
        [12, 10]],

       [[19, 17],
        [10, 19],
        [17, 11],
        [12, 11],
        [19, 12]],

       [[13, 18],
        [13, 14],
        [13, 11],
        [19, 16],
        [15, 13]]])

In [ ]:
# [10, 20) 10 이상 20 미만
# (19, 20] 10초과 20 이하

# 10 이상 20 미만
# 3차원 배열
np.random.randint(0, 100, (3, 5, 2))

array([[[ 0, 65],
        [11, 67],
        [75, 44],
        [ 0,  9],
        [47, 49]],

       [[74, 96],
        [20, 67],
        [57, 36],
        [77, 92],
        [49, 97]],

       [[97, 99],
        [26, 55],
        [ 4, 99],
        [ 7, 20],
        [53, 44]]])

## seed()
    - 난수를 예측가능하도록 만든다. 실행할 때마다 동일한 난수가 발생하도록 한다.
    - 재현성 : 특정 알고리즘의 결과를 재현한다.
    - 디버깅 : 해당 알고리즘의 결과로 오류를 추적한다.



In [ ]:
# seed(시작값)
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
# e-01: 지수 표기법
# 숫자가 너무 작거나 클때 사용하는 과학적 표기법
np.random.seed(1)
np.random.rand(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

## np.unique()
    - 중복된 값을 제거하고 고유한 값들만 반환하는 함수

In [ ]:
np.unique([11, 10, 11, 20, 15, 10])

array([10, 11, 15, 20])

## 인덱싱(index)
    - 파이썬 리스트와 동일한 계념으로 사용
    - ,를 사용하여 각 차원의 인덱스에 접근이 가능하다.
    - 인덱싱 할 때 마다 차원이 감소한다.

In [ ]:
ar2 = np.arange(10)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(ar2[5])

5


In [ ]:
print(ar2[-1], ar2[4])

9 4


In [ ]:
ar2[5] = 100
ar2

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [ ]:
ar2 = ar2.reshape(2, 5)
ar2[0][2]

np.int64(2)

In [ ]:
ar2[1][0]

np.int64(100)

In [ ]:
# , 를 통해서 접근하는법
# 권장, 콤마 접근법
ar2[1,0]

np.int64(100)